/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'rasen-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`rasen list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`rasen status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

3. **Check task completion status (HARD GATE)**

   Read the tasks file from \`artifactPaths.tasks.existingOutputPaths\` (in the status JSON fetched in step 2) to check for incomplete tasks — resolve it from the CLI rather than assuming a repo-local \`tasks.md\` (the tasks artifact is not always literally \`tasks.md\`), matching \`rasen-bulk-archive-change\`.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found — this is a HARD GATE (aligned with verify's "must fix before archive"):**
   - Display the count of incomplete tasks and REFUSE to archive by default.
   - Proceed ONLY on an explicit override that NAMES the incomplete-task condition (e.g. the user selects "Archive anyway despite N incomplete tasks") — not the routine confirm.
   - In a non-interactive / dispatched context, REFUSE outright — do not auto-confirm.

   **If no tasks file exists:** Proceed without task-related warning.

3.5. **Check verification verdict (HARD GATE)**

   Read \`verification-report.md\` from the work directory (\`workDir\` from status JSON; fall back to the change directory — \`changeRoot\` — when \`workDir\` is absent or the file already lives there) when it exists, and honor its \`VERIFY VERDICT:\` line (written by \`/rasen:verify\` — capability \`verify-ship-evidence\`; do NOT invent new verdict words).
   - \`VERIFY VERDICT: BLOCKED\` → HARD GATE: REFUSE to archive by default; proceed only on an explicit, blocker-naming user override (e.g. "Archive anyway despite BLOCKED verification"); REFUSE outright non-interactively.
   - \`VERIFY VERDICT: CLEAN\` → no verification-related gate; proceed.
   - No \`verification-report.md\` → do NOT hard-gate on verification absence (a change may legitimately archive without a formal verify pass); a soft note at most.

3.6. **Check delivery precondition (soft)**

   Read \`ship-log.md\` from the work directory (\`workDir\` from status JSON; fall back to the change directory — \`changeRoot\` — when \`workDir\` is absent or the file already lives there):
   - **Absent** → soft-warn "This change has no ship log — archive without delivering?" with an explicit escape for changes that legitimately do not ship (e.g. spec-only); proceed on confirm.
   - **Present and its \`Status:\` line contains "delivery deferred to portfolio level"** (the marker ship writes in local mode) → soft note that parent-level portfolio delivery is still pending and archiving the child now may lose track of it; confirm to proceed. Minimal cross-reference only — no portfolio graph or parent lookup.
   - **Present and delivery completed** (PR created / branch pushed) → proceed without a delivery warning.

4. **Assess delta spec sync state**

   Use \`artifactPaths.specs.existingOutputPaths\` from status JSON to check for delta specs. If none exist, proceed without sync prompt.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec, resolved under the \`specs/\` directory that is the sibling of \`planningHome.changesDir\` (from the status JSON in step 2), NOT a literal repo-relative \`rasen/specs/<capability>/spec.md\` — in a registered store this resolves to the store's specs
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   If user chooses sync, use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke rasen-sync-specs for change '<name>'. Delta spec analysis: <include the analyzed delta spec summary>"). Proceed to archive regardless of choice.

5. **Perform the archive**

   Create an \`archive\` directory under \`planningHome.changesDir\` if it doesn't exist:
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move \`changeRoot\` to the archive directory

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Whether specs were synced (if applicable)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs (or "No delta specs" or "Sync skipped")

All artifacts complete. All tasks complete.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (rasen status --json) for completion checking
- **Hard gates vs soft warnings (precedence).** REFUSE archive by default on the two HARD GATES — a \`VERIFY VERDICT: BLOCKED\` verification report (Step 3.5) and incomplete tasks (Step 3): proceed only on an explicit blocker-naming override, and refuse outright non-interactively. The "don't block archive on warnings — just inform and confirm" rule applies ONLY to SOFT warnings (incomplete non-task artifacts, unsynced delta specs, missing ship log, portfolio-deferred delivery); it does NOT cover the two hard gates.
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, use rasen-sync-specs approach (agent-driven)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting`,
    license: 'MIT',
    compatibility: 'Requires rasen CLI.',
    metadata: { author: 'rasen', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'Rasen: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/rasen:archive\` (e.g., \`/rasen:archive add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`rasen list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`rasen status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **Check task completion status (HARD GATE)**

   Read the tasks file from \`artifactPaths.tasks.existingOutputPaths\` (in the status JSON fetched in step 2) to check for incomplete tasks — resolve it from the CLI rather than assuming a repo-local \`tasks.md\` (the tasks artifact is not always literally \`tasks.md\`), matching \`rasen-bulk-archive-change\`.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found — this is a HARD GATE (aligned with verify's "must fix before archive"):**
   - Display the count of incomplete tasks and REFUSE to archive by default.
   - Proceed ONLY on an explicit override that NAMES the incomplete-task condition (e.g. the user replies "Archive anyway despite N incomplete tasks") — not the routine confirm.
   - In a non-interactive / dispatched context, REFUSE outright — do not auto-confirm.

   **If no tasks file exists:** Proceed without task-related warning.

3.5. **Check verification verdict (HARD GATE)**

   Read \`verification-report.md\` from the work directory (\`workDir\` from status JSON; fall back to the change directory — \`changeRoot\` — when \`workDir\` is absent or the file already lives there) when it exists, and honor its \`VERIFY VERDICT:\` line (written by \`/rasen:verify\` — capability \`verify-ship-evidence\`; do NOT invent new verdict words).
   - \`VERIFY VERDICT: BLOCKED\` → HARD GATE: REFUSE to archive by default; proceed only on an explicit, blocker-naming user override (e.g. "Archive anyway despite BLOCKED verification"); REFUSE outright non-interactively.
   - \`VERIFY VERDICT: CLEAN\` → no verification-related gate; proceed.
   - No \`verification-report.md\` → do NOT hard-gate on verification absence (a change may legitimately archive without a formal verify pass); a soft note at most.

3.6. **Check delivery precondition (soft)**

   Read \`ship-log.md\` from the work directory (\`workDir\` from status JSON; fall back to the change directory — \`changeRoot\` — when \`workDir\` is absent or the file already lives there):
   - **Absent** → soft-warn "This change has no ship log — archive without delivering?" with an explicit escape for changes that legitimately do not ship (e.g. spec-only); proceed on confirm.
   - **Present and its \`Status:\` line contains "delivery deferred to portfolio level"** (the marker ship writes in local mode) → soft note that parent-level portfolio delivery is still pending and archiving the child now may lose track of it; confirm to proceed. Minimal cross-reference only — no portfolio graph or parent lookup.
   - **Present and delivery completed** (PR created / branch pushed) → proceed without a delivery warning.

4. **Assess delta spec sync state**

   Use \`artifactPaths.specs.existingOutputPaths\` from status JSON to check for delta specs. If none exist, proceed without sync prompt.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec, resolved under the \`specs/\` directory that is the sibling of \`planningHome.changesDir\` (from the status JSON in step 2), NOT a literal repo-relative \`rasen/specs/<capability>/spec.md\` — in a registered store this resolves to the store's specs
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   If user chooses sync, use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke rasen-sync-specs for change '<name>'. Delta spec analysis: <include the analyzed delta spec summary>"). Proceed to archive regardless of choice.

5. **Perform the archive**

   Create an \`archive\` directory under \`planningHome.changesDir\` if it doesn't exist:
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move \`changeRoot\` to the archive directory

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Spec sync status (synced / sync skipped / no delta specs)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (No Delta Specs)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** No delta specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success With Warnings**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** Sync skipped (user chose to skip)

**Warnings:**
- Archived with 2 incomplete artifacts (soft warning)
- Archived despite 3 incomplete tasks — explicit override (hard gate)
- Archived despite BLOCKED verification — explicit override (hard gate) [only if a BLOCKED verification-report.md was overridden]
- No ship log — archived without delivering (soft warning) [only if applicable]
- Delta spec sync was skipped (user chose to skip)

Review the archive if this was not intentional.
\`\`\`

**Output On Error (Archive Exists)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Target:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/

Target archive directory already exists.

**Options:**
1. Rename the existing archive
2. Delete the existing archive if it's a duplicate
3. Wait until a different date to archive
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (rasen status --json) for completion checking
- **Hard gates vs soft warnings (precedence).** REFUSE archive by default on the two HARD GATES — a \`VERIFY VERDICT: BLOCKED\` verification report (Step 3.5) and incomplete tasks (Step 3): proceed only on an explicit blocker-naming override, and refuse outright non-interactively. The "don't block archive on warnings — just inform and confirm" rule applies ONLY to SOFT warnings (incomplete non-task artifacts, unsynced delta specs, missing ship log, portfolio-deferred delivery); it does NOT cover the two hard gates.
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, use the Skill tool to invoke \`rasen-sync-specs\` (agent-driven)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting`
  };
}
