/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'rasen-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run rasen-apply-change

---

${STORE_SELECTION_GUIDANCE}

**Methodology consult (optional):** For design-dense changes — a new module or a non-trivial interface — consult the \`rasen-codebase-design\` skill (deep-module design, design-it-twice) before writing specs. Capture the resulting interface/design decisions in this change's \`design.md\` Decisions section (or a change-directory sidecar resolved from \`rasen status --json\` \`changeRoot\`). This is a conditional reference, not a required step; don't inline the expert body.

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name — the **verbatim** kebab-case of the description, with NO abbreviation (e.g., "real-time collaboration" → \`real-time-collaboration\`). \`/office-hours\` derives its topic slug the same verbatim way, so a matching description yields the same name and the office-hours sibling-dir doc (Step 3.5) is auto-detected.

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   rasen new change "<name>"
   \`\`\`
   This creates a scaffolded change in the planning home resolved by the CLI with \`.openspec.yaml\`.

3. **Get the artifact build order**
   \`\`\`bash
   rasen status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context. Use these instead of assuming repo-local paths.

3.5. **Check for office-hours validation and read it as input context (if present)**

   Office-hours may already have produced a design/validation doc for this topic. Before drafting, look for it in TWO locations, both resolved from the status JSON (do NOT hardcode \`rasen/...\` paths):
   - **(a) Active-change case:** \`office-hours-design.md\` inside \`changeRoot\`.
   - **(b) No-active-change case:** \`<change-name>.md\` in the \`office-hours\` directory alongside the changes directory (derive it from \`planningHome.changesDir\` — the \`office-hours\` sibling of that changes dir). This is discoverable because \`/office-hours\` derives its filename slug the SAME way \`rasen-propose\` derives a change name, so when the change name matches the topic slug the file lines up.

   If either file is found, READ it and incorporate its findings/decisions (problem framing, demand evidence, chosen approach, premises) into the proposal, naming office-hours as the source context. If neither exists, proceed normally — office-hours is optional input, not a precondition. (Best-effort: if the change name differs from the office-hours slug the sibling-dir file won't be found; the user may point you at it.)

4. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        rasen instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`resolvedOutputPath\`: Resolved path or pattern to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure and write it to \`resolvedOutputPath\`
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`rasen status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show final status**
   \`\`\`bash
   rasen status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`rasen-apply-change\` or ask me to implement to start working on the tasks."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`rasen instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output
- Bulky raw research material (scratch probing logs, fetched corpora, long transcripts) belongs in the work directory's \`research/\` area (\`workDir\` from status JSON, absent → skip this) — never in a committed artifact; distill conclusions into \`design.md\` or a slim committed research doc instead

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires rasen CLI.',
    metadata: { author: 'rasen', version: '1.0' },
  };
}
