// Types
export {
  StageSchema,
  StageRoleSchema,
  AgentRuntimeSchema,
  AgentRuntimeSessionReuseSchema,
  AgentRuntimeSandboxSchema,
  AgentRuntimeConfigSchema,
  AgentRuntimeConfigValueSchema,
  PipelineAgentRuntimeOverridesSchema,
  normalizeAgentRuntimeConfig,
  resolveStageRuntimeConfig,
  resolveStageHandoffConfig,
  resolvePipelineReuseConfig,
  StageLoopSchema,
  LOOP_KIND_VALUES,
  StageKindSchema,
  VerifyPolicySchema,
  PipelineYamlSchema,
  PipelineDefinitionVersionSchema,
  PIPELINE_DEFINITION_VERSION,
  HandoffConfigSchema,
  ReuseConfigSchema,
  ReuseModeSchema,
  DEFAULT_CHILD_PIPELINE,
  DEFAULT_HANDOFF_CONFIG,
  DEFAULT_REUSE_CONFIG,
  UNKNOWN_HOST_RUNTIME,
  type Stage,
  type StageRole,
  type AgentRuntime,
  type AgentRuntimeSessionReuse,
  type AgentRuntimeSandbox,
  type AgentRuntimeConfig,
  type PipelineAgentRuntimeOverrides,
  type ResolvedStageRuntimeConfig,
  type ResolvedStageHandoffConfig,
  type HandoffConfigLayers,
  type ModelConfigLayers,
  type ModelSource,
  type RuntimeSource,
  type RuntimeResolutionContext,
  type StageOverride,
  type StageOverrideScope,
  type StageConfigOverrides,
  type ResolvedReuseConfig,
  type ThresholdResolutionContext,
  type HandoffConfig,
  type ReuseConfig,
  type ReuseMode,
  type StageLoop,
  type StageKind,
  type VerifyPolicy,
  type PipelineYaml,
  type CompletedSet,
  type BlockedStages,
  type ThresholdValue,
} from './types.js';

// Pipeline loading and validation
export {
  loadPipeline,
  parsePipeline,
  parsePipelineSourceDocument,
  serializePipelineYaml,
  validatePreparedLegacyPipeline,
  validatePreparedLegacyPipelineDraft,
  collectLegacyPipelineSkillIssues,
  validatePipelineSkills,
  validatePipelineDraft,
  PipelineValidationError,
  pipelineValidationErrorFromDefinitionReadError,
  type PipelineValidationIssue,
} from './pipeline.js';

// Executable Composite Pipeline Definition v2 preparation. This is the one
// authoritative semantic seam shared by registry, management, and Canvas.
export {
  EcpDefinitionModule,
  ECP_DEFINITION_VERSION,
  ECP_NODE_KINDS,
  CHANGE_RUN_PLAN_VERSION,
  CAPABILITY_CATALOG_VERSION,
  V2_RUNTIME_UNAVAILABLE_REASON,
  DefinitionReadError,
  createCapabilityCatalogSnapshot,
  createProductionCapabilityCatalogSnapshot,
  createBlankPipelineDefinitionV2,
  orderDefinitionDiagnostics,
  serializeAuthoredPipelineDefinition,
  type DefinitionSource,
  type DefinitionSourceV2,
  type DefinitionPort,
  type DefinitionArtifact,
  type AtomicStageExecutionV1,
  type DefinitionNode,
  type DefinitionGraph,
  type DefinitionConnection,
  type CompositeDeclaration,
  type DefinitionDiagnostic,
  type DefinitionDiagnosticCode,
  type CapabilityDescriptor,
  type CapabilityCatalogSnapshot,
  type ProductionCapabilityDefinition,
  type ChangeRunPlan,
  type PreparedDefinition,
  type PreparedBoundedLoopPolicy,
  type DefinitionPreparationResult,
} from './definition.js';
export {
  preflightPreparedDefinitionExecution,
  resolvePipelineExecutionSkillSets,
  validatePipelineForExecution,
  validatePreparedPipelineForExecution,
  type PreparedDefinitionExecutionSelection,
  type PipelineExecutionSkillSets,
  type PipelineExecutionOptions,
} from './execution-validation.js';
export {
  freezeProductionPreparedPipelineRegistry,
  type FreezePreparedPipelineRegistryOptions,
  type PreparedPipelineExecution,
  type ProductionPreparedPipelineRegistry,
} from './prepared-registry.js';
export {
  projectPreparedPipelineExecutionView,
  type PreparedExecutionStageView,
  type PreparedExecutionCapabilityPathView,
  type PreparedExecutionPolicyPathView,
  type PreparedPipelineExecutionView,
  type PreparedExecutionViewInputs,
} from './prepared-execution-view.js';
export {
  CHANGE_LEVEL_BUILTIN_PIPELINES,
  PIPELINE_V1_COMPATIBILITY_FIXTURES,
  PIPELINE_V1_COMPATIBILITY_BOUNDARIES,
  pipelineV1CompatibilityBoundary,
  type ChangeLevelBuiltinPipeline,
  type PipelineV1CompatibilityFixture,
  type PipelineCompatibilityBoundary,
} from './builtins.js';

// Per-pipeline stage-override resolver + gate mask (config top layer)
export {
  bucketPipelineStageOverrides,
  resolvePipelineStageOverrides,
  resolveMaskedStageGate,
  resolveEffectiveStage,
  resolvePipelineRoleRuntimes,
  resolvePipelineExecutionPlan,
  stageConfigOverridesFor,
  type PipelineStageOverrides,
  type MaskedStageGate,
  type MaskedGateSource,
  type EffectiveStageConfig,
  type EffectiveStageInputs,
  type ResolvedRoleRuntime,
  type RoleRuntimeSource,
  type ExecutionStageRuntime,
  type PipelineExecutionPlan,
  type PipelineExecutionPlanInputs,
} from './stage-overrides.js';

// Graph operations
export { PipelineGraph } from './graph.js';

// Completion-set state helpers
export {
  createCompletedSet,
  markCompleted,
  unmarkCompleted,
  isStageCompleted,
} from './state.js';

// Run-state (auto-run.json) — typed contract for resume/observability
export {
  RUN_STATE_FILENAME,
  RunStateSchema,
  RunStateStageSchema,
  RunStateWorkerSchema,
  StageStatusSchema,
  StageHandoffRecordSchema,
  SessionHandoffSchema,
  RunStateValidationError,
  runStatePath,
  parseRunState,
  readRunState,
  readRunStateDetailed,
  writeRunState,
  initializeRunState,
  resolveRunStateLocation,
  resolveLegacyOwnerSignal,
  stateFileSearchChain,
  completedStages,
  frozenRetentionMode,
  frozenKnowledgeContext,
  frozenExecutionBinding,
  RETAIN_STAGE_ID,
  normalizeWorker,
  normalizeRunStateWorkerRecord,
  inferWorkerDispatchMode,
  stageWorkers,
  stagesWithStatus,
  stagesLackingDurableHandle,
  detectDuplicateKeys,
  latestStageHandoffs,
  sessionHandoffGeneration,
  type RunState,
  type RunStateStage,
  type RunStateWorker,
  type RunStateDispatchMode,
  type WorkerDispatchInference,
  type StageStatus,
  type StageHandoffRecord,
  type SessionHandoff,
  type RunStateLocation,
  type StateFileLocationOptions,
  type RunStateReadResult,
  type LegacyOwnerSignal,
  type RunStatePipelineSeed,
} from './run-state.js';

// Frozen-resume execution binding (unified-session-runtime-context D4)
export {
  resolveFrozenExecutionBinding,
  checkoutsMatch,
  type ExecutionBindingErrorCode,
  type ExecutionBindingFailure,
  type ExecutionBindingResult,
  type ResolveFrozenExecutionInput,
} from './execution-binding.js';

// Pipeline resolution
export {
  loadPipelineByName,
  loadPreparedPipelineByName,
  resolvePipelinePath,
  resolvePipelineSource,
  listPipelines,
  listPipelinesWithInfo,
  getPipelineDir,
  getPackagePipelinesDir,
  getUserPipelinesDir,
  getProjectPipelinesDir,
  resolveChildPipelineName,
  validateDecomposeChildPipelines,
  PipelineLoadError,
  type PipelineInfo,
  type PipelineSourceLayer,
  type PipelinePreparationOptions,
  type PreparedPipelineResolution,
} from './resolver.js';

// Legacy skill-ID recognition (resume old->new hinting)
export { mapLegacySkillId } from './legacy-skill.js';

export {
  createTrustedExecutionAdapterCatalog,
  createTrustedExecutionAdapterProducerResolver,
  loadTrustedExecutionAdapterCatalog,
  provisionTrustedExecutionAdapterCatalog,
  provisionTrustedExecutionAdapterCredentials,
  resolveTrustedExecutionAdapterAuthority,
  trustedExecutionAdapterCatalogPath,
  trustedExecutionAdapterCredentialPath,
  TrustedExecutionAdapterError,
  PACKAGE_UNAVAILABLE_AUTHORITY,
  type TrustedExecutionAdapterCatalog,
  type TrustedExecutionAdapterCredentialInput,
  type TrustedExecutionAdapterDescriptor,
} from './trusted-execution-adapters.js';

// Portfolio run-state (portfolio-run.json) — multi-change observability + resume
export {
  PORTFOLIO_STATE_FILENAME,
  PortfolioStateSchema,
  PortfolioChildSchema,
  PortfolioChildStatusSchema,
  PortfolioDeliverySchema,
  PortfolioDeliveryStatusSchema,
  ChildExecutionModeSchema,
  PortfolioStateValidationError,
  portfolioStatePath,
  parsePortfolioState,
  readPortfolioState,
  readPortfolioStateDetailed,
  writePortfolioState,
  resolvePortfolioStateLocation,
  runnableChildren,
  interruptedChildren,
  escalatedChildren,
  arePortfolioChildrenComplete,
  isPortfolioComplete,
  type PortfolioState,
  type PortfolioChild,
  type PortfolioChildStatus,
  type PortfolioStateReadResult,
  type PortfolioDelivery,
  type PortfolioDeliveryStatus,
  type ChildExecutionMode,
  type PortfolioStateLocation,
} from './portfolio-state.js';
