// Types
export {
  StageSchema,
  StageRoleSchema,
  AgentRuntimeSchema,
  AgentRuntimeSessionReuseSchema,
  AgentRuntimeSandboxSchema,
  AgentRuntimeConfigSchema,
  AgentRuntimeConfigValueSchema,
  PipelineAgentRuntimeOverridesSchema,
  normalizeAgentRuntimeConfig,
  resolveStageRuntimeConfig,
  resolveStageHandoffConfig,
  resolvePipelineReuseConfig,
  StageLoopSchema,
  LOOP_KIND_VALUES,
  StageKindSchema,
  VerifyPolicySchema,
  PipelineYamlSchema,
  PipelineDefinitionVersionSchema,
  PIPELINE_DEFINITION_VERSION,
  HandoffConfigSchema,
  ReuseConfigSchema,
  ReuseModeSchema,
  DEFAULT_CHILD_PIPELINE,
  DEFAULT_HANDOFF_CONFIG,
  DEFAULT_REUSE_CONFIG,
  UNKNOWN_HOST_RUNTIME,
  type Stage,
  type StageRole,
  type AgentRuntime,
  type AgentRuntimeSessionReuse,
  type AgentRuntimeSandbox,
  type AgentRuntimeConfig,
  type PipelineAgentRuntimeOverrides,
  type ResolvedStageRuntimeConfig,
  type ResolvedStageHandoffConfig,
  type HandoffConfigLayers,
  type ModelConfigLayers,
  type ModelSource,
  type RuntimeSource,
  type RuntimeResolutionContext,
  type StageOverride,
  type StageOverrideScope,
  type StageConfigOverrides,
  type ResolvedReuseConfig,
  type ThresholdResolutionContext,
  type HandoffConfig,
  type ReuseConfig,
  type ReuseMode,
  type StageLoop,
  type StageKind,
  type VerifyPolicy,
  type PipelineYaml,
  type CompletedSet,
  type BlockedStages,
  type ThresholdValue,
} from './types.js';

// Pipeline loading and validation
export {
  loadPipeline,
  parsePipeline,
  serializePipelineYaml,
  validatePipelineSkills,
  validatePipelineDraft,
  PipelineValidationError,
  type PipelineValidationIssue,
} from './pipeline.js';
export {
  resolvePipelineExecutionSkillSets,
  validatePipelineForExecution,
  type PipelineExecutionSkillSets,
  type PipelineExecutionOptions,
} from './execution-validation.js';

// Per-pipeline stage-override resolver + gate mask (config top layer)
export {
  bucketPipelineStageOverrides,
  resolvePipelineStageOverrides,
  resolveMaskedStageGate,
  resolveEffectiveStage,
  resolvePipelineRoleRuntimes,
  resolvePipelineExecutionPlan,
  stageConfigOverridesFor,
  type PipelineStageOverrides,
  type MaskedStageGate,
  type MaskedGateSource,
  type EffectiveStageConfig,
  type EffectiveStageInputs,
  type ResolvedRoleRuntime,
  type RoleRuntimeSource,
  type ExecutionStageRuntime,
  type PipelineExecutionPlan,
  type PipelineExecutionPlanInputs,
} from './stage-overrides.js';

// Graph operations
export { PipelineGraph } from './graph.js';

// Completion-set state helpers
export {
  createCompletedSet,
  markCompleted,
  unmarkCompleted,
  isStageCompleted,
} from './state.js';

// Run-state (auto-run.json) — typed contract for resume/observability
export {
  RUN_STATE_FILENAME,
  RunStateSchema,
  RunStateStageSchema,
  RunStateWorkerSchema,
  StageStatusSchema,
  StageHandoffRecordSchema,
  SessionHandoffSchema,
  RunStateValidationError,
  runStatePath,
  parseRunState,
  readRunState,
  readRunStateDetailed,
  writeRunState,
  createRunStateExclusive,
  updateRunStateKnowledgeContext,
  initializeRunState,
  resolveRunStateLocation,
  stateFileSearchChain,
  completedStages,
  frozenRetentionMode,
  frozenKnowledgeContext,
  frozenExecutionBinding,
  RETAIN_STAGE_ID,
  normalizeWorker,
  normalizeRunStateWorkerRecord,
  inferWorkerDispatchMode,
  stageWorkers,
  stagesWithStatus,
  stagesLackingDurableHandle,
  detectDuplicateKeys,
  latestStageHandoffs,
  sessionHandoffGeneration,
  type RunState,
  type RunStateStage,
  type RunStateWorker,
  type RunStateDispatchMode,
  type WorkerDispatchInference,
  type StageStatus,
  type StageHandoffRecord,
  type SessionHandoff,
  type RunStateLocation,
  type StateFileLocationOptions,
  type RunStateReadResult,
  type RunStatePipelineSeed,
  type RunStateCreateResult,
  type RunStateContextUpdateResult,
  type RunStateContextUpdateRefusal,
} from './run-state.js';

// Frozen-resume execution binding (unified-session-runtime-context D4)
export {
  resolveFrozenExecutionBinding,
  checkoutsMatch,
  type ExecutionBindingErrorCode,
  type ExecutionBindingFailure,
  type ExecutionBindingResult,
  type ResolveFrozenExecutionInput,
} from './execution-binding.js';

// Pipeline resolution
export {
  loadPipelineByName,
  resolvePipelinePath,
  listPipelines,
  listPipelinesWithInfo,
  getPipelineDir,
  getPackagePipelinesDir,
  getUserPipelinesDir,
  getProjectPipelinesDir,
  resolveChildPipelineName,
  validateDecomposeChildPipelines,
  PipelineLoadError,
  type PipelineInfo,
} from './resolver.js';

// Legacy skill-ID recognition (resume old->new hinting)
export { mapLegacySkillId } from './legacy-skill.js';

// Portfolio run-state (portfolio-run.json) — multi-change observability + resume
export {
  PORTFOLIO_STATE_FILENAME,
  PortfolioStateSchema,
  PortfolioChildSchema,
  PortfolioChildStatusSchema,
  PortfolioDeliverySchema,
  PortfolioDeliveryStatusSchema,
  ChildExecutionModeSchema,
  PortfolioStateValidationError,
  portfolioStatePath,
  parsePortfolioState,
  readPortfolioState,
  readPortfolioStateDetailed,
  writePortfolioState,
  resolvePortfolioStateLocation,
  runnableChildren,
  interruptedChildren,
  escalatedChildren,
  arePortfolioChildrenComplete,
  isPortfolioComplete,
  type PortfolioState,
  type PortfolioChild,
  type PortfolioChildStatus,
  type PortfolioStateReadResult,
  type PortfolioDelivery,
  type PortfolioDeliveryStatus,
  type ChildExecutionMode,
  type PortfolioStateLocation,
} from './portfolio-state.js';
