/**
 * Per-project machine-local debounce marker for the skill/CLI version-
 * mismatch ambient warning (delivery-reliability-version-guard).
 *
 * `resolveRootForCommand` (root-selection.ts) already detects, on every
 * project-scoped command, whether a configured tool's installed skills were
 * generated by a CLI version different from the one currently running
 * (`getAllToolVersionStatus`). Printing that warning on every single
 * invocation would be correct but noisy for the failure mode that actually
 * matters here: an AI-agent session driving dozens of project-scoped
 * commands back-to-back against the same stale install.
 *
 * This module stores the last (installed stamp version, running CLI
 * version) pair the warning fired for, in the project's own machine-local
 * home directory (`resolveProjectHome`'s `homeDir` — the same entry point
 * `expert-selection-state.ts` uses for its per-project marker). The warning
 * fires again the moment the pair changes: `rasen update` advances the
 * stamp, or the CLI itself is upgraded again mid-session.
 *
 * Best-effort throughout, mirroring `expert-selection-state.ts` exactly: a
 * read/write failure (missing home, corrupt marker file, filesystem error)
 * is never a command failure, it just means the debounce state is treated
 * as absent — worst case is an extra warning line, never a wrong result.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

/** Exported for tests that need to simulate a project with no prior marker. */
export const VERSION_GUARD_MARKER_FILE_NAME = 'version-guard-last-warned.json';

export interface LastWarnedVersionPair {
  stampVersion: string;
  cliVersion: string;
}

/**
 * Reads the last (stampVersion, cliVersion) pair the mismatch warning fired
 * for in `homeDir`'s project. Returns null when no marker exists, or when
 * the marker is missing/unreadable/malformed — a corrupt marker is treated
 * exactly like "no marker" rather than thrown.
 */
export function readLastWarnedVersionPair(homeDir: string): LastWarnedVersionPair | null {
  try {
    const raw = fs.readFileSync(path.join(homeDir, VERSION_GUARD_MARKER_FILE_NAME), 'utf-8');
    const parsed: unknown = JSON.parse(raw);
    if (
      parsed !== null &&
      typeof parsed === 'object' &&
      typeof (parsed as Record<string, unknown>).stampVersion === 'string' &&
      typeof (parsed as Record<string, unknown>).cliVersion === 'string'
    ) {
      const record = parsed as { stampVersion: string; cliVersion: string };
      return { stampVersion: record.stampVersion, cliVersion: record.cliVersion };
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Records that the mismatch warning has fired for `pair` in `homeDir`'s
 * project. Best-effort and silent on failure: a write failure just means
 * the next project-scoped command re-evaluates from "no marker" rather than
 * corrupting state or throwing mid-command.
 */
export function writeLastWarnedVersionPair(homeDir: string, pair: LastWarnedVersionPair): void {
  try {
    fs.mkdirSync(homeDir, { recursive: true });
    fs.writeFileSync(
      path.join(homeDir, VERSION_GUARD_MARKER_FILE_NAME),
      JSON.stringify({ ...pair, warnedAt: new Date().toISOString() }, null, 2) + '\n',
      'utf-8'
    );
  } catch {
    // Best-effort; see module docstring above.
  }
}
